logging:
  file: ${user.dir}/logs/psc.log
spring:
  datasource:
    jmx-enabled: true
    type: org.apache.tomcat.jdbc.pool.DataSource
  flyway:
    locations: db/migration
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
  thymeleaf:
    mode: HTML5
psc:
  admin:
    username: root
    password: b5371f7d-06b1-44be-a781-46b71a6caeaa
    domain: localhost